config/routes.rb
EmploymentAgency::Application.routes.draw do

  match '/employees/create_new_skill',    to: 'employees#create_new_skill'
  match '/vacancies/create_new_skill',    to: 'vacancies#create_new_skill'

  match 'employees/:id/vacancies', to: 'employees#vacancies', as: 'vacancies_for_employee'
  match 'vacancies/:id/employees', to: 'vacancies#employees', as: 'employees_for_vacancy'

  root to: 'static_pages#home'
  resources :employees, only: [:new, :create, :edit, :update, :index]
  resources :vacancies, only: [:new, :create, :edit, :update, :index]

end

app/models/employee.rb
#encoding: utf-8
class Employee < ActiveRecord::Base
	include DatabaseHelper

	attr_accessible :contact_info, :desired_salary, :looking_for_work, :name
	has_many :skill_relationships, class_name: "EmployeeSkillRelationship", dependent: :destroy
	has_many :skills, through: :skill_relationships

	before_validation do |employee|
		employee.name = employee.name.gsub(/\s+/, ' ').strip
	end

  validates :desired_salary, presence: true, numericality: { only_integer: true }
  validates :contact_info, presence: true

  # FIXME: if format is wrong - a message "is invalid" appears, instead of specified one
  validates :name, presence: true, format: { with: /^(([\p{Cyrillic}]+)\s){2}\p{Cyrillic}+$/,
  				   			 											 messsage: "Name should consist from 3 cyrillic words" }
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	include ParamsHelper

	def new
		@employee = Employee.new
		@need_work = true
	end

	def vacancies
		@employee = Employee.find(params[:id])
		@exact_match_vacancies = @employee.get_exact_match_vacancies
		@fuzzy_match_vacancies = @employee.get_fuzzy_match_vacancies(@exact_match_vacancies)
	end

	def index
		@employees = Employee.paginate(page: params[:page])
	end

	def edit
		@employee = Employee.find(params[:id])
		@existing_skill_ids = @employee.skills.map { |skill| skill.id.to_s }
		@need_work = @employee.looking_for_work

		render 'new'
	end

	def update
		@employee = Employee.find(params[:id])
		if @employee.update_attributes(params[:employee])
			flash.now[:success] = "Employee successfully updated!"
		end
		@employee.delete_all_skills
		@employee.add_skills(get_new_skill_names, get_existing_skill_ids)

		# WTF: @employee.skills returns empty array, although we just added skills
		# Because of it we have to use Employee#skill_relationships to get skills IDs
		@existing_skill_ids = @employee.skill_relationships.map { |relationship| relationship.skill_id.to_s }
		@need_work = params[:employee][:looking_for_work] == "1"

		render 'new'
	end

	def create
		@employee = Employee.new(params[:employee])
		if @employee.save
			flash.now[:success] = "New Employee #{params[:employee][:name]} Created"
			@employee.add_skills(get_new_skill_names, get_existing_skill_ids)
			reset_object_state
		else
			@new_skill_names = get_new_skill_names
			@existing_skill_ids = get_existing_skill_ids
			@need_work = params[:employee][:looking_for_work] == "1"
		end
		render 'new'
	end

	def create_new_skill
		respond_to do |format|
       		format.js { render 'shared/create_new_skill' }
    	end
	end

private
	def reset_object_state
		@employee = Employee.new
		@new_skill_names = []
		@existing_skill_ids = []
		@need_work = true
	end
end

app/helpers/employees_helper.rb
module EmployeesHelper

	def number_of_elements_in(container)
		if container.nil?
			0
		else
			container.count
		end
	end

	def checked?(skill_id, collection)
		if collection.nil?
			false
		else
			collection.include?(skill_id.to_s)
		end
	end

	def highlight_skill(need_highlight)
		"highlight" if need_highlight
	end

	def record_number_for(index)
		page = params[:page] ? params[:page] : "1"
		WillPaginate.per_page * (page.to_i - 1) + index
	end
end

app/views/employees/_fuzzy_match_table.html.erb
<table border="1" id="fuzzy_match_table">
	<thead>
		<th>Name</th>
		<th>Salary, $</th>
		<th>Need to learn</th>
	</thead>
	<tbody>
		<% Vacancy.order("salary DESC").find(@fuzzy_match_vacancies).each do |vacancy| %>
		<tr>
			<td>
				<%= link_to vacancy.name, edit_vacancy_path(vacancy.id) %></td>
			<td>
				<%= vacancy.salary %></td>
				<td>
					<% missing_skills = vacancy.skills - @employee.skills %>
					<% missing_skills.each do |skill| %>
						<span class="missing_skill"><%= skill.name %></span>
					<% end %>
				</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/employees/_perfect_match_table.html.erb
<table border="1" id="perfect_match_table">
	<thead>
		<th>Name</th>
		<th>Salary, $</th>
		<th>Required skills</th>
	</thead>
	<tbody>
		<% Vacancy.order("salary DESC").find(@exact_match_vacancies).each do |vacancy| %>
		<tr>
			<td>
				<%= link_to vacancy.name, edit_vacancy_path(vacancy.id) %></td>
			<td>
				<%= vacancy.salary %></td>
				<td>
					<% vacancy.skills.each do |skill| %>
						<%= skill.name %>
					<% end %>
				</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/employees/index.html.erb
<% provide(:title, "Employees list") %>
<h1>Employees list</h1>
<%= will_paginate %>
<table border="1">
	<thead>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th colspan="2">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @employees.each_with_index do |employee, index| %>
			<tr>
				<td><%= record_number_for index + 1 %></td>
				<td><%= employee.name %></td>
				<td><%= link_to "edit", edit_employee_path(employee) %></td>
				<td><%= link_to "find work", vacancies_for_employee_path(employee) %></td>
			</tr>
		<% end %>
	</tbody>
</table>
<%= will_paginate %>
<%= link_to "Back", root_path %>

app/views/employees/new.html.erb
<% provide(:title, page_title_for(@employee)) %>
<h1><%= page_title_for @employee %></h1>

<%= form_for(@employee) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<%= f.label :name %>
	<%= f.text_field :name, placeholder: "Введите 3 русских слова" %>

	<%= f.label :desired_salary %>
	<%= f.text_field :desired_salary, placeholder: "USA Dollars" %>

	<%= f.label :contact_info %>
	<%= f.text_field :contact_info, placeholder: "Phone or Email" %>

	<%= f.label :looking_for_work %>
	<%= f.check_box :looking_for_work, checked: @need_work %>

	Skills (<%= link_to "Add new", {action: 'create_new_skill'}, remote: true %>)
	<%= render 'shared/new_skills' %>
	<%= render 'shared/skills_table', f:f %>

    <%= f.submit %>
<% end %>

<%= link_to "Back", back_path_for(@employee) %>

app/views/employees/vacancies.html.erb
<% provide(:title, "Vacancies for employee: #{@employee.name}") %>
<h1>Vacancies for employee: <%= @employee.name %></h1>
<p>Knows:
	<% @employee.skills.each do |skill| %>
		<%= skill.name %>
	<% end %>
</p>
<p>Wants: <%= @employee.desired_salary %>$</p>

<h2>Perfect match</h2>
<%= render 'employees/perfect_match_table' %>

<h2>Need to learn a thing or two</h2>
<%= render 'employees/fuzzy_match_table' %>

<%= link_to "Back", employees_path %>