config/routes.rb
EmploymentAgency::Application.routes.draw do

  match '/employees/create_new_skill',    to: 'employees#create_new_skill'
  match '/vacancies/create_new_skill',    to: 'vacancies#create_new_skill'

  match 'employees/:id/vacancies', to: 'employees#vacancies', as: 'vacancies_for_employee'
  match 'vacancies/:id/employees', to: 'vacancies#employees', as: 'employees_for_vacancy'

  root to: 'static_pages#home'
  resources :employees, only: [:new, :create, :edit, :update, :index]
  resources :vacancies, only: [:new, :create, :edit, :update, :index]

end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  include DatabaseHelper
  serialize :elapsed, Hash
  attr_accessible :added, :contact_info, :elapsed, :name, :salary
  has_many :skill_relationships, class_name: "VacancySkillRelationship", dependent: :destroy
  has_many :skills, through: :skill_relationships

  validates :name, presence: true
  validates :salary, presence: true, numericality: { only_integer: true }
  validates :contact_info, presence: true
  validates :added, presence: true
  validates :elapsed, presence: true

  def expired?
  	Date.today > elapsed_to_date
  end

private
  def elapsed_to_date
	elapsed = self.added
	elapsed += self.elapsed[:days].to_i.days
	elapsed += self.elapsed[:months].to_i.months
	elapsed += self.elapsed[:years].to_i.years
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
	include ParamsHelper

	def new
		@vacancy = Vacancy.new
	end

	def index
		@vacancies = Vacancy.paginate(page: params[:page])
	end

	def employees
		@vacancy = Vacancy.find(params[:id])
		@exact_match_employees = @vacancy.get_exact_match_employees
		@fuzzy_match_employees = @vacancy.get_fuzzy_match_employees(@exact_match_employees)
	end

	def edit
		@vacancy = Vacancy.find(params[:id])
		@existing_skill_ids = @vacancy.skills.map { |skill| skill.id.to_s }
		render 'new'
	end

	def update
		@vacancy = Vacancy.find(params[:id])
		if @vacancy.update_attributes(params[:vacancy])
			if @vacancy.update_attribute(:elapsed, params[:elapsed])
				flash.now[:success] = "Vacancy successfully updated!"
			end
		end
		@vacancy.delete_all_skills
		@vacancy.add_skills(get_new_skill_names, get_existing_skill_ids)

		# WTF: @vacancy.skills returns empty array, although we just added skills
		# Because of it we have to use Vacancy#skill_relationships to get skills IDs
		@existing_skill_ids = @vacancy.skill_relationships.map { |relationship| relationship.skill_id.to_s }

		render 'new'
	end

	def create
		@vacancy = Vacancy.new(params[:vacancy])
		@vacancy.elapsed = params[:elapsed]
		if @vacancy.save
			flash.now[:success] = "New Vacancy #{params[:vacancy][:name]} Created"
			@vacancy.add_skills(get_new_skill_names, get_existing_skill_ids)
			reset_object_state
		else
			@new_skill_names = get_new_skill_names
			@existing_skill_ids = get_existing_skill_ids
		end
		render 'new'
	end

	def create_new_skill
		respond_to do |format|
       		format.js { render 'shared/create_new_skill'}
    	end
	end

private
	def reset_object_state
		@vacancy = Vacancy.new
		@new_skill_names = []
		@existing_skill_ids = []
	end
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
	def generate_years_list
		(1..10).map do |value|
			["In #{pluralize(value, 'year')}", value]
		end
	end

	def generate_months_list
		(1..12).map do |value|
			["#{pluralize(value, 'month')}", value]
		end
	end

	def generate_days_list
		(1..31).map do |value|
			["#{pluralize(value, 'day')}", value]
		end
	end

	def selected_year(hash)
		hash[:years] unless hash.nil?
	end

	def selected_day(hash)
		hash[:days] unless hash.nil?
	end

	def selected_month(hash)
		if hash.nil? || hash.empty?
			6
		else
			hash[:months]
		end
	end
end

app/views/vacancies/_elapsed_control.html.erb
<%= f.label :elapsed %>
<%= select_tag "elapsed[years]",
				options_for_select(generate_years_list, selected_year(@vacancy.elapsed)),
				prompt: "In 0 years" %>

<%= select_tag "elapsed[months]",
				options_for_select(generate_months_list, selected_month(@vacancy.elapsed)),
				prompt: "0 months" %>

<%= select_tag "elapsed[days]",
				options_for_select(generate_days_list, selected_day(@vacancy.elapsed)),
				prompt: "0 days" %>

app/views/vacancies/_fuzzy_match_table.html.erb
<table border="1" id="fuzzy_match_table">
	<thead>
		<th>Name</th>
		<th>Salary, $</th>
		<th>Missing skills</th>
		<th>Extra skills</th>
	</thead>
	<tbody>
		<% Employee.order(:desired_salary).find(@fuzzy_match_employees).each do |employee| %>
		<tr>
			<td>
				<%= link_to employee.name, edit_employee_path(employee.id) %></td>
			<td>
				<%= employee.desired_salary %>
			</td>
			<td>
				<% missing_skills = @vacancy.skills - employee.skills %>
				<% missing_skills.each do |skill| %>
					<span class="missing_skill"><%= skill.name %></span>
				<% end %>
			</td>
			<td>
				<% extra_skills = employee.skills - @vacancy.skills %>
				<% if !extra_skills.empty? %>
					<% extra_skills.each do |skill| %>
						<span class="extra_skill"><%= skill.name %></span>
					<% end %>
				<% else %>
					none
				<% end %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/vacancies/_perfect_match_table.html.erb
<table border="1" id="perfect_match_table">
	<thead>
		<th>Name</th>
		<th>Salary, $</th>
		<th>Extra skills</th>
	</thead>
	<tbody>
		<% Employee.order(:desired_salary).find(@exact_match_employees).each do |employee| %>
		<tr>
			<td>
				<%= link_to employee.name, edit_employee_path(employee.id) %></td>
			<td>
				<%= employee.desired_salary %></td>
				<td>
					<% extra_skills = employee.skills - @vacancy.skills %>
					<% if !extra_skills.empty? %>
						<% extra_skills.each do |skill| %>
							<span class="extra_skill"><%= skill.name %></span>
						<% end %>
					<% else %>
						none
					<% end %>
				</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/vacancies/employees.html.erb
<% provide(:title, "Employees for vacancy: \"#{@vacancy.name}\"") %>
<h1>Employees for vacancy: "<%= @vacancy.name %>"</h1>
<p>Required skills:
	<% @vacancy.skills.each do |skill| %>
		<%= skill.name %>
	<% end %>
</p>
<p>Salary: <%= @vacancy.salary %>$</p>

<h2>Perfect match</h2>
<%= render 'vacancies/perfect_match_table' %>

<h2>Some skills are missing</h2>
<%= render 'vacancies/fuzzy_match_table' %>

<%= link_to "Back", vacancies_path %>

app/views/vacancies/index.html.erb
<% provide(:title, "Vacancies list") %>
<h1>Vacancies list</h1>
<%= will_paginate %>
<table border="1">
	<thead>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th colspan="2">Action</th>
		</tr>
	</thead>
	<tbody>
		<% @vacancies.each_with_index do |vacancy, index| %>
			<tr>
				<td><%= record_number_for index + 1 %></td>
				<td><%= vacancy.name %></td>
				<td><%= link_to "edit", edit_vacancy_path(vacancy) %></td>
				<td><%= link_to "find worker", employees_for_vacancy_path(vacancy) %>
			</tr>
		<% end %>
	</tbody>
</table>
<%= will_paginate %>
<%= link_to "Back", root_path %>

app/views/vacancies/new.html.erb
<% provide(:title, page_title_for(@vacancy)) %>
<h1><%= page_title_for @vacancy %></h1>

<%= form_for(@vacancy) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :salary %>
	<%= f.text_field :salary, placeholder: "USA Dollars" %>

	<%= f.label :contact_info %>
	<%= f.text_field :contact_info, placeholder: "Phone or Email" %>

	<%= f.label :added %>
	<%= f.date_select :added, order: [:day, :month, :year] %>

	<br>
	<%= render 'elapsed_control', f: f %>
	<br>
	<br>

	Desired skills (<%= link_to "Add new", {action: 'create_new_skill'}, remote: true %>)
	<%= render 'shared/new_skills' %>
	<%= render 'shared/skills_table', f: f %>

    <%= f.submit %>
<% end %>

<%= link_to "Back", back_path_for(@vacancy) %>